apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 370639238640.dkr.ecr.us-east-1.amazonaws.com/bestcloud/spring-boot-app 
        ports:
        - containerPort: 8080